from setuptools import setup, find_packages

setup(name='pyRHESSys',
      version='1.0.0',
      description='an Object-Oriented Python wrapper for the RHESSys model',
      url='https://github.com/DavidChoi76/pyRHESSys.git',
      author='YoungDon Choi',
      author_email='choiyd1115@gmail.com',
      license='MIT',
      packages=find_packages(),
      install_requires=[
          'numpy>=1.11.2',
          'xarray>0.10.9',
          'matplotlib',
          'netcdf4>=1.2.5',
          'numba',
          'pandas',
          'hs_restclient',
          'scipy>=0.18.1',
          'dask==2.12.0',
          'distributed>=2.5.2',
          'toolz',
          'dask-jobqueue',
          'geopandas',
          'holoviews==1.12.7',
          'bokeh==1.4.0',
          'geoviews==1.6.6',
          'hydroeval',
          'imageio'
          ],
      include_package_data=True,
      test_suite='pyRHESSys.tests')
